name: 'Terraform Core'

on:
  repository_dispatch:
    types: [apm]

permissions:
  contents: read

jobs:

  # Run the APM workflow
  apm:
    name: APM
    uses: ./.github/workflows/apm.yml
    with:
      newrelic_account_id: ${{ github.event.client_payload.newrelic_account_id }}
      newrelic_api_key: ${{ github.event.client_payload.newrelic_api_key }}
      newrelic_region: ${{ github.event.client_payload.newrelic_region }}
      app_name: ${{ github.event.client_payload.app_name }}
      terraform_destroy: ${{ github.event.client_payload.terraform_destroy }}
    secrets:
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
